#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 131
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 44
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 1

enum {
  aux_sym_Stmt_token1 = 1,
  aux_sym_Stmt_token2 = 2,
  anon_sym_EQ = 3,
  anon_sym_DOT = 4,
  anon_sym_LPAREN = 5,
  anon_sym_RPAREN = 6,
  anon_sym_LT = 7,
  anon_sym_LT_EQ = 8,
  anon_sym_GT = 9,
  anon_sym_GT_EQ = 10,
  anon_sym_PLUS = 11,
  anon_sym_DASH = 12,
  anon_sym_STAR = 13,
  anon_sym_SLASH = 14,
  sym_ID = 15,
  sym_STR = 16,
  sym_NUM = 17,
  aux_sym_CR_token1 = 18,
  aux_sym_CR_token2 = 19,
  sym_EndIf = 20,
  sym_Start = 21,
  sym_Prog = 22,
  sym_MoreThanOneStmt = 23,
  sym_Stmt = 24,
  sym_MoreThanZeroElseIf = 25,
  sym_OptionalElse = 26,
  sym_ExprStatement = 27,
  sym_CRStmtCRs = 28,
  sym_TheRest = 29,
  sym_Exprs = 30,
  sym_MoreThanOneExpr = 31,
  sym_Expr = 32,
  sym_CondExpr = 33,
  sym_OrExpr = 34,
  sym_AndExpr = 35,
  sym_EqNeqExpr = 36,
  sym_CompExpr = 37,
  sym_AdditiveExpr = 38,
  sym_MultiplicativeExpr = 39,
  sym_UnaryExpr = 40,
  sym_Primary = 41,
  sym_CR = 42,
  aux_sym_Start_repeat1 = 43,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_Stmt_token1] = "Stmt_token1",
  [aux_sym_Stmt_token2] = "Stmt_token2",
  [anon_sym_EQ] = "=",
  [anon_sym_DOT] = ".",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LT] = "<",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT] = ">",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [sym_ID] = "ID",
  [sym_STR] = "STR",
  [sym_NUM] = "NUM",
  [aux_sym_CR_token1] = "CR_token1",
  [aux_sym_CR_token2] = "CR_token2",
  [sym_EndIf] = "EndIf",
  [sym_Start] = "Start",
  [sym_Prog] = "Prog",
  [sym_MoreThanOneStmt] = "MoreThanOneStmt",
  [sym_Stmt] = "Stmt",
  [sym_MoreThanZeroElseIf] = "MoreThanZeroElseIf",
  [sym_OptionalElse] = "OptionalElse",
  [sym_ExprStatement] = "ExprStatement",
  [sym_CRStmtCRs] = "CRStmtCRs",
  [sym_TheRest] = "TheRest",
  [sym_Exprs] = "Exprs",
  [sym_MoreThanOneExpr] = "MoreThanOneExpr",
  [sym_Expr] = "Expr",
  [sym_CondExpr] = "CondExpr",
  [sym_OrExpr] = "OrExpr",
  [sym_AndExpr] = "AndExpr",
  [sym_EqNeqExpr] = "EqNeqExpr",
  [sym_CompExpr] = "CompExpr",
  [sym_AdditiveExpr] = "AdditiveExpr",
  [sym_MultiplicativeExpr] = "MultiplicativeExpr",
  [sym_UnaryExpr] = "UnaryExpr",
  [sym_Primary] = "Primary",
  [sym_CR] = "CR",
  [aux_sym_Start_repeat1] = "Start_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_Stmt_token1] = aux_sym_Stmt_token1,
  [aux_sym_Stmt_token2] = aux_sym_Stmt_token2,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_ID] = sym_ID,
  [sym_STR] = sym_STR,
  [sym_NUM] = sym_NUM,
  [aux_sym_CR_token1] = aux_sym_CR_token1,
  [aux_sym_CR_token2] = aux_sym_CR_token2,
  [sym_EndIf] = sym_EndIf,
  [sym_Start] = sym_Start,
  [sym_Prog] = sym_Prog,
  [sym_MoreThanOneStmt] = sym_MoreThanOneStmt,
  [sym_Stmt] = sym_Stmt,
  [sym_MoreThanZeroElseIf] = sym_MoreThanZeroElseIf,
  [sym_OptionalElse] = sym_OptionalElse,
  [sym_ExprStatement] = sym_ExprStatement,
  [sym_CRStmtCRs] = sym_CRStmtCRs,
  [sym_TheRest] = sym_TheRest,
  [sym_Exprs] = sym_Exprs,
  [sym_MoreThanOneExpr] = sym_MoreThanOneExpr,
  [sym_Expr] = sym_Expr,
  [sym_CondExpr] = sym_CondExpr,
  [sym_OrExpr] = sym_OrExpr,
  [sym_AndExpr] = sym_AndExpr,
  [sym_EqNeqExpr] = sym_EqNeqExpr,
  [sym_CompExpr] = sym_CompExpr,
  [sym_AdditiveExpr] = sym_AdditiveExpr,
  [sym_MultiplicativeExpr] = sym_MultiplicativeExpr,
  [sym_UnaryExpr] = sym_UnaryExpr,
  [sym_Primary] = sym_Primary,
  [sym_CR] = sym_CR,
  [aux_sym_Start_repeat1] = aux_sym_Start_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_Stmt_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_Stmt_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_ID] = {
    .visible = true,
    .named = true,
  },
  [sym_STR] = {
    .visible = true,
    .named = true,
  },
  [sym_NUM] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_CR_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_CR_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_EndIf] = {
    .visible = true,
    .named = true,
  },
  [sym_Start] = {
    .visible = true,
    .named = true,
  },
  [sym_Prog] = {
    .visible = true,
    .named = true,
  },
  [sym_MoreThanOneStmt] = {
    .visible = true,
    .named = true,
  },
  [sym_Stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_MoreThanZeroElseIf] = {
    .visible = true,
    .named = true,
  },
  [sym_OptionalElse] = {
    .visible = true,
    .named = true,
  },
  [sym_ExprStatement] = {
    .visible = true,
    .named = true,
  },
  [sym_CRStmtCRs] = {
    .visible = true,
    .named = true,
  },
  [sym_TheRest] = {
    .visible = true,
    .named = true,
  },
  [sym_Exprs] = {
    .visible = true,
    .named = true,
  },
  [sym_MoreThanOneExpr] = {
    .visible = true,
    .named = true,
  },
  [sym_Expr] = {
    .visible = true,
    .named = true,
  },
  [sym_CondExpr] = {
    .visible = true,
    .named = true,
  },
  [sym_OrExpr] = {
    .visible = true,
    .named = true,
  },
  [sym_AndExpr] = {
    .visible = true,
    .named = true,
  },
  [sym_EqNeqExpr] = {
    .visible = true,
    .named = true,
  },
  [sym_CompExpr] = {
    .visible = true,
    .named = true,
  },
  [sym_AdditiveExpr] = {
    .visible = true,
    .named = true,
  },
  [sym_MultiplicativeExpr] = {
    .visible = true,
    .named = true,
  },
  [sym_UnaryExpr] = {
    .visible = true,
    .named = true,
  },
  [sym_Primary] = {
    .visible = true,
    .named = true,
  },
  [sym_CR] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_Start_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 2,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 8,
  [11] = 7,
  [12] = 8,
  [13] = 9,
  [14] = 14,
  [15] = 14,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 16,
  [26] = 26,
  [27] = 17,
  [28] = 28,
  [29] = 16,
  [30] = 17,
  [31] = 26,
  [32] = 28,
  [33] = 18,
  [34] = 24,
  [35] = 26,
  [36] = 22,
  [37] = 19,
  [38] = 23,
  [39] = 24,
  [40] = 20,
  [41] = 21,
  [42] = 21,
  [43] = 23,
  [44] = 20,
  [45] = 18,
  [46] = 28,
  [47] = 19,
  [48] = 22,
  [49] = 49,
  [50] = 50,
  [51] = 49,
  [52] = 50,
  [53] = 53,
  [54] = 49,
  [55] = 55,
  [56] = 50,
  [57] = 57,
  [58] = 58,
  [59] = 57,
  [60] = 57,
  [61] = 61,
  [62] = 58,
  [63] = 58,
  [64] = 61,
  [65] = 61,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 67,
  [71] = 69,
  [72] = 67,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 75,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 86,
  [89] = 89,
  [90] = 90,
  [91] = 82,
  [92] = 77,
  [93] = 76,
  [94] = 94,
  [95] = 78,
  [96] = 73,
  [97] = 79,
  [98] = 87,
  [99] = 90,
  [100] = 83,
  [101] = 78,
  [102] = 81,
  [103] = 103,
  [104] = 94,
  [105] = 79,
  [106] = 76,
  [107] = 74,
  [108] = 77,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 110,
  [114] = 114,
  [115] = 111,
  [116] = 116,
  [117] = 109,
  [118] = 111,
  [119] = 112,
  [120] = 120,
  [121] = 109,
  [122] = 112,
  [123] = 123,
  [124] = 124,
  [125] = 116,
  [126] = 126,
  [127] = 127,
  [128] = 123,
  [129] = 114,
  [130] = 130,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(15);
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == '*') ADVANCE(30);
      if (lookahead == '+') ADVANCE(28);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == '<') ADVANCE(24);
      if (lookahead == '=') ADVANCE(19);
      if (lookahead == '>') ADVANCE(26);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(38);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(35);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(36);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(45);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == '*') ADVANCE(30);
      if (lookahead == '+') ADVANCE(28);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == '<') ADVANCE(24);
      if (lookahead == '>') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(1)
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(44);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == '*') ADVANCE(30);
      if (lookahead == '+') ADVANCE(28);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == '<') ADVANCE(24);
      if (lookahead == '>') ADVANCE(26);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(1)
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(4);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == '.') ADVANCE(13);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(3)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(41);
      if (lookahead != 0) ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == ')') ADVANCE(23);
      if (lookahead == '*') ADVANCE(30);
      if (lookahead == '+') ADVANCE(28);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == '<') ADVANCE(24);
      if (lookahead == '>') ADVANCE(26);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(11);
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(5)
      END_STATE();
    case 6:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(10);
      END_STATE();
    case 7:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(46);
      END_STATE();
    case 9:
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(7);
      END_STATE();
    case 10:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(8);
      END_STATE();
    case 11:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 12:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 14:
      if (eof) ADVANCE(15);
      if (lookahead == '(') ADVANCE(22);
      if (lookahead == '*') ADVANCE(30);
      if (lookahead == '+') ADVANCE(28);
      if (lookahead == '-') ADVANCE(29);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == '<') ADVANCE(24);
      if (lookahead == '=') ADVANCE(19);
      if (lookahead == '>') ADVANCE(26);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(14)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(aux_sym_Stmt_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_Stmt_token2);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_Stmt_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(27);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_ID);
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_ID);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_ID);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_ID);
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_ID);
      if (lookahead == 'H' ||
          lookahead == 'h') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_ID);
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_ID);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_ID);
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_ID);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_STR);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_NUM);
      if (lookahead == '.') ADVANCE(13);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_NUM);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_CR_token1);
      if (lookahead == '\n') ADVANCE(45);
      if (lookahead == '\r') ADVANCE(2);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_CR_token2);
      if (lookahead == '\n') ADVANCE(45);
      if (lookahead == '\r') ADVANCE(2);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_EndIf);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 14},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 3},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 3},
  [14] = {.lex_state = 3},
  [15] = {.lex_state = 3},
  [16] = {.lex_state = 14},
  [17] = {.lex_state = 14},
  [18] = {.lex_state = 14},
  [19] = {.lex_state = 14},
  [20] = {.lex_state = 14},
  [21] = {.lex_state = 14},
  [22] = {.lex_state = 14},
  [23] = {.lex_state = 14},
  [24] = {.lex_state = 14},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 14},
  [27] = {.lex_state = 5},
  [28] = {.lex_state = 14},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 5},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 5},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 5},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 5},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 14},
  [50] = {.lex_state = 3},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 3},
  [53] = {.lex_state = 14},
  [54] = {.lex_state = 5},
  [55] = {.lex_state = 14},
  [56] = {.lex_state = 3},
  [57] = {.lex_state = 3},
  [58] = {.lex_state = 14},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 5},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 14},
  [67] = {.lex_state = 14},
  [68] = {.lex_state = 14},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 5},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 14},
  [74] = {.lex_state = 14},
  [75] = {.lex_state = 5},
  [76] = {.lex_state = 14},
  [77] = {.lex_state = 14},
  [78] = {.lex_state = 14},
  [79] = {.lex_state = 14},
  [80] = {.lex_state = 5},
  [81] = {.lex_state = 14},
  [82] = {.lex_state = 14},
  [83] = {.lex_state = 14},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 14},
  [86] = {.lex_state = 14},
  [87] = {.lex_state = 14},
  [88] = {.lex_state = 14},
  [89] = {.lex_state = 14},
  [90] = {.lex_state = 14},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 1},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 1},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 1},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 5},
  [102] = {.lex_state = 1},
  [103] = {.lex_state = 14},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 5},
  [106] = {.lex_state = 5},
  [107] = {.lex_state = 1},
  [108] = {.lex_state = 5},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 3},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 3},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 3},
  [120] = {.lex_state = 5},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 3},
  [123] = {.lex_state = 5},
  [124] = {.lex_state = 5},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 5},
  [129] = {.lex_state = 3},
  [130] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_Stmt_token1] = ACTIONS(1),
    [aux_sym_Stmt_token2] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [sym_ID] = ACTIONS(1),
    [sym_STR] = ACTIONS(1),
    [sym_NUM] = ACTIONS(1),
    [sym_EndIf] = ACTIONS(1),
  },
  [1] = {
    [sym_Start] = STATE(130),
    [sym_Prog] = STATE(53),
    [sym_MoreThanOneStmt] = STATE(85),
    [sym_Stmt] = STATE(89),
    [sym_ExprStatement] = STATE(74),
    [aux_sym_Start_repeat1] = STATE(53),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_Stmt_token1] = ACTIONS(5),
    [sym_ID] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(11), 1,
      anon_sym_RPAREN,
    ACTIONS(13), 1,
      sym_ID,
    STATE(32), 1,
      sym_MultiplicativeExpr,
    STATE(36), 1,
      sym_UnaryExpr,
    STATE(37), 1,
      sym_Primary,
    STATE(54), 1,
      sym_AdditiveExpr,
    STATE(63), 1,
      sym_CompExpr,
    STATE(101), 1,
      sym_OrExpr,
    STATE(105), 1,
      sym_CondExpr,
    STATE(106), 1,
      sym_EqNeqExpr,
    STATE(108), 1,
      sym_AndExpr,
    STATE(117), 1,
      sym_Exprs,
    STATE(126), 1,
      sym_MoreThanOneExpr,
    STATE(127), 1,
      sym_Expr,
    ACTIONS(15), 2,
      sym_STR,
      sym_NUM,
  [50] = 16,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_ID,
    ACTIONS(17), 1,
      anon_sym_RPAREN,
    STATE(32), 1,
      sym_MultiplicativeExpr,
    STATE(36), 1,
      sym_UnaryExpr,
    STATE(37), 1,
      sym_Primary,
    STATE(54), 1,
      sym_AdditiveExpr,
    STATE(63), 1,
      sym_CompExpr,
    STATE(101), 1,
      sym_OrExpr,
    STATE(105), 1,
      sym_CondExpr,
    STATE(106), 1,
      sym_EqNeqExpr,
    STATE(108), 1,
      sym_AndExpr,
    STATE(109), 1,
      sym_Exprs,
    STATE(126), 1,
      sym_MoreThanOneExpr,
    STATE(127), 1,
      sym_Expr,
    ACTIONS(15), 2,
      sym_STR,
      sym_NUM,
  [100] = 16,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_ID,
    ACTIONS(19), 1,
      anon_sym_RPAREN,
    STATE(32), 1,
      sym_MultiplicativeExpr,
    STATE(36), 1,
      sym_UnaryExpr,
    STATE(37), 1,
      sym_Primary,
    STATE(54), 1,
      sym_AdditiveExpr,
    STATE(63), 1,
      sym_CompExpr,
    STATE(101), 1,
      sym_OrExpr,
    STATE(105), 1,
      sym_CondExpr,
    STATE(106), 1,
      sym_EqNeqExpr,
    STATE(108), 1,
      sym_AndExpr,
    STATE(121), 1,
      sym_Exprs,
    STATE(126), 1,
      sym_MoreThanOneExpr,
    STATE(127), 1,
      sym_Expr,
    ACTIONS(15), 2,
      sym_STR,
      sym_NUM,
  [150] = 15,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_ID,
    STATE(32), 1,
      sym_MultiplicativeExpr,
    STATE(36), 1,
      sym_UnaryExpr,
    STATE(37), 1,
      sym_Primary,
    STATE(54), 1,
      sym_AdditiveExpr,
    STATE(63), 1,
      sym_CompExpr,
    STATE(101), 1,
      sym_OrExpr,
    STATE(105), 1,
      sym_CondExpr,
    STATE(106), 1,
      sym_EqNeqExpr,
    STATE(108), 1,
      sym_AndExpr,
    STATE(125), 1,
      sym_Exprs,
    STATE(126), 1,
      sym_MoreThanOneExpr,
    STATE(127), 1,
      sym_Expr,
    ACTIONS(15), 2,
      sym_STR,
      sym_NUM,
  [197] = 15,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_ID,
    STATE(32), 1,
      sym_MultiplicativeExpr,
    STATE(36), 1,
      sym_UnaryExpr,
    STATE(37), 1,
      sym_Primary,
    STATE(54), 1,
      sym_AdditiveExpr,
    STATE(63), 1,
      sym_CompExpr,
    STATE(101), 1,
      sym_OrExpr,
    STATE(105), 1,
      sym_CondExpr,
    STATE(106), 1,
      sym_EqNeqExpr,
    STATE(108), 1,
      sym_AndExpr,
    STATE(116), 1,
      sym_Exprs,
    STATE(126), 1,
      sym_MoreThanOneExpr,
    STATE(127), 1,
      sym_Expr,
    ACTIONS(15), 2,
      sym_STR,
      sym_NUM,
  [244] = 13,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_ID,
    STATE(46), 1,
      sym_MultiplicativeExpr,
    STATE(47), 1,
      sym_Primary,
    STATE(48), 1,
      sym_UnaryExpr,
    STATE(51), 1,
      sym_AdditiveExpr,
    STATE(62), 1,
      sym_CompExpr,
    STATE(92), 1,
      sym_AndExpr,
    STATE(93), 1,
      sym_EqNeqExpr,
    STATE(95), 1,
      sym_OrExpr,
    STATE(97), 1,
      sym_CondExpr,
    STATE(99), 1,
      sym_Expr,
    ACTIONS(25), 2,
      sym_STR,
      sym_NUM,
  [285] = 13,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_ID,
    STATE(32), 1,
      sym_MultiplicativeExpr,
    STATE(36), 1,
      sym_UnaryExpr,
    STATE(37), 1,
      sym_Primary,
    STATE(54), 1,
      sym_AdditiveExpr,
    STATE(63), 1,
      sym_CompExpr,
    STATE(101), 1,
      sym_OrExpr,
    STATE(105), 1,
      sym_CondExpr,
    STATE(106), 1,
      sym_EqNeqExpr,
    STATE(108), 1,
      sym_AndExpr,
    STATE(111), 1,
      sym_Expr,
    ACTIONS(15), 2,
      sym_STR,
      sym_NUM,
  [326] = 13,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_ID,
    STATE(32), 1,
      sym_MultiplicativeExpr,
    STATE(36), 1,
      sym_UnaryExpr,
    STATE(37), 1,
      sym_Primary,
    STATE(54), 1,
      sym_AdditiveExpr,
    STATE(63), 1,
      sym_CompExpr,
    STATE(101), 1,
      sym_OrExpr,
    STATE(105), 1,
      sym_CondExpr,
    STATE(106), 1,
      sym_EqNeqExpr,
    STATE(108), 1,
      sym_AndExpr,
    STATE(128), 1,
      sym_Expr,
    ACTIONS(15), 2,
      sym_STR,
      sym_NUM,
  [367] = 13,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_ID,
    STATE(32), 1,
      sym_MultiplicativeExpr,
    STATE(36), 1,
      sym_UnaryExpr,
    STATE(37), 1,
      sym_Primary,
    STATE(54), 1,
      sym_AdditiveExpr,
    STATE(63), 1,
      sym_CompExpr,
    STATE(101), 1,
      sym_OrExpr,
    STATE(105), 1,
      sym_CondExpr,
    STATE(106), 1,
      sym_EqNeqExpr,
    STATE(108), 1,
      sym_AndExpr,
    STATE(115), 1,
      sym_Expr,
    ACTIONS(15), 2,
      sym_STR,
      sym_NUM,
  [408] = 13,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      sym_ID,
    STATE(19), 1,
      sym_Primary,
    STATE(22), 1,
      sym_UnaryExpr,
    STATE(28), 1,
      sym_MultiplicativeExpr,
    STATE(49), 1,
      sym_AdditiveExpr,
    STATE(58), 1,
      sym_CompExpr,
    STATE(76), 1,
      sym_EqNeqExpr,
    STATE(77), 1,
      sym_AndExpr,
    STATE(78), 1,
      sym_OrExpr,
    STATE(79), 1,
      sym_CondExpr,
    STATE(90), 1,
      sym_Expr,
    ACTIONS(31), 2,
      sym_STR,
      sym_NUM,
  [449] = 13,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_ID,
    STATE(32), 1,
      sym_MultiplicativeExpr,
    STATE(36), 1,
      sym_UnaryExpr,
    STATE(37), 1,
      sym_Primary,
    STATE(54), 1,
      sym_AdditiveExpr,
    STATE(63), 1,
      sym_CompExpr,
    STATE(101), 1,
      sym_OrExpr,
    STATE(105), 1,
      sym_CondExpr,
    STATE(106), 1,
      sym_EqNeqExpr,
    STATE(108), 1,
      sym_AndExpr,
    STATE(118), 1,
      sym_Expr,
    ACTIONS(15), 2,
      sym_STR,
      sym_NUM,
  [490] = 13,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_ID,
    STATE(32), 1,
      sym_MultiplicativeExpr,
    STATE(36), 1,
      sym_UnaryExpr,
    STATE(37), 1,
      sym_Primary,
    STATE(54), 1,
      sym_AdditiveExpr,
    STATE(63), 1,
      sym_CompExpr,
    STATE(101), 1,
      sym_OrExpr,
    STATE(105), 1,
      sym_CondExpr,
    STATE(106), 1,
      sym_EqNeqExpr,
    STATE(108), 1,
      sym_AndExpr,
    STATE(123), 1,
      sym_Expr,
    ACTIONS(15), 2,
      sym_STR,
      sym_NUM,
  [531] = 13,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_ID,
    STATE(46), 1,
      sym_MultiplicativeExpr,
    STATE(47), 1,
      sym_Primary,
    STATE(48), 1,
      sym_UnaryExpr,
    STATE(51), 1,
      sym_AdditiveExpr,
    STATE(62), 1,
      sym_CompExpr,
    STATE(92), 1,
      sym_AndExpr,
    STATE(93), 1,
      sym_EqNeqExpr,
    STATE(95), 1,
      sym_OrExpr,
    STATE(96), 1,
      sym_Expr,
    STATE(97), 1,
      sym_CondExpr,
    ACTIONS(25), 2,
      sym_STR,
      sym_NUM,
  [572] = 13,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      sym_ID,
    STATE(19), 1,
      sym_Primary,
    STATE(22), 1,
      sym_UnaryExpr,
    STATE(28), 1,
      sym_MultiplicativeExpr,
    STATE(49), 1,
      sym_AdditiveExpr,
    STATE(58), 1,
      sym_CompExpr,
    STATE(73), 1,
      sym_Expr,
    STATE(76), 1,
      sym_EqNeqExpr,
    STATE(77), 1,
      sym_AndExpr,
    STATE(78), 1,
      sym_OrExpr,
    STATE(79), 1,
      sym_CondExpr,
    ACTIONS(31), 2,
      sym_STR,
      sym_NUM,
  [613] = 3,
    ACTIONS(37), 1,
      anon_sym_DOT,
    ACTIONS(35), 4,
      aux_sym_Stmt_token1,
      anon_sym_LT,
      anon_sym_GT,
      sym_ID,
    ACTIONS(33), 7,
      ts_builtin_sym_end,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [632] = 3,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 4,
      aux_sym_Stmt_token1,
      anon_sym_LT,
      anon_sym_GT,
      sym_ID,
    ACTIONS(39), 7,
      ts_builtin_sym_end,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [651] = 2,
    ACTIONS(35), 4,
      aux_sym_Stmt_token1,
      anon_sym_LT,
      anon_sym_GT,
      sym_ID,
    ACTIONS(33), 7,
      ts_builtin_sym_end,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [667] = 2,
    ACTIONS(47), 4,
      aux_sym_Stmt_token1,
      anon_sym_LT,
      anon_sym_GT,
      sym_ID,
    ACTIONS(45), 7,
      ts_builtin_sym_end,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [683] = 3,
    ACTIONS(53), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(51), 4,
      aux_sym_Stmt_token1,
      anon_sym_LT,
      anon_sym_GT,
      sym_ID,
    ACTIONS(49), 5,
      ts_builtin_sym_end,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [701] = 2,
    ACTIONS(57), 4,
      aux_sym_Stmt_token1,
      anon_sym_LT,
      anon_sym_GT,
      sym_ID,
    ACTIONS(55), 7,
      ts_builtin_sym_end,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [717] = 2,
    ACTIONS(61), 4,
      aux_sym_Stmt_token1,
      anon_sym_LT,
      anon_sym_GT,
      sym_ID,
    ACTIONS(59), 7,
      ts_builtin_sym_end,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [733] = 2,
    ACTIONS(65), 4,
      aux_sym_Stmt_token1,
      anon_sym_LT,
      anon_sym_GT,
      sym_ID,
    ACTIONS(63), 7,
      ts_builtin_sym_end,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [749] = 2,
    ACTIONS(69), 4,
      aux_sym_Stmt_token1,
      anon_sym_LT,
      anon_sym_GT,
      sym_ID,
    ACTIONS(67), 7,
      ts_builtin_sym_end,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [765] = 2,
    ACTIONS(71), 1,
      anon_sym_DOT,
    ACTIONS(35), 10,
      anon_sym_LT,
      anon_sym_LT_EQ,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [781] = 2,
    ACTIONS(41), 4,
      aux_sym_Stmt_token1,
      anon_sym_LT,
      anon_sym_GT,
      sym_ID,
    ACTIONS(39), 7,
      ts_builtin_sym_end,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [797] = 3,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(39), 8,
      aux_sym_Stmt_token2,
      anon_sym_RPAREN,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [815] = 3,
    ACTIONS(53), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(77), 4,
      aux_sym_Stmt_token1,
      anon_sym_LT,
      anon_sym_GT,
      sym_ID,
    ACTIONS(75), 5,
      ts_builtin_sym_end,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [833] = 3,
    ACTIONS(79), 1,
      anon_sym_DOT,
    ACTIONS(35), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 8,
      aux_sym_Stmt_token2,
      anon_sym_RPAREN,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [851] = 2,
    ACTIONS(81), 1,
      anon_sym_LPAREN,
    ACTIONS(41), 10,
      anon_sym_LT,
      anon_sym_LT_EQ,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [867] = 1,
    ACTIONS(41), 10,
      anon_sym_LT,
      anon_sym_LT_EQ,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [880] = 3,
    ACTIONS(77), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(83), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(75), 6,
      aux_sym_Stmt_token2,
      anon_sym_RPAREN,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [897] = 2,
    ACTIONS(35), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(33), 8,
      aux_sym_Stmt_token2,
      anon_sym_RPAREN,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [912] = 1,
    ACTIONS(69), 10,
      anon_sym_LT,
      anon_sym_LT_EQ,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [925] = 2,
    ACTIONS(41), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(39), 8,
      aux_sym_Stmt_token2,
      anon_sym_RPAREN,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [940] = 2,
    ACTIONS(61), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 8,
      aux_sym_Stmt_token2,
      anon_sym_RPAREN,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [955] = 2,
    ACTIONS(47), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(45), 8,
      aux_sym_Stmt_token2,
      anon_sym_RPAREN,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [970] = 1,
    ACTIONS(65), 10,
      anon_sym_LT,
      anon_sym_LT_EQ,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [983] = 2,
    ACTIONS(69), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(67), 8,
      aux_sym_Stmt_token2,
      anon_sym_RPAREN,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [998] = 3,
    ACTIONS(51), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(83), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(49), 6,
      aux_sym_Stmt_token2,
      anon_sym_RPAREN,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
  [1015] = 2,
    ACTIONS(57), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(55), 8,
      aux_sym_Stmt_token2,
      anon_sym_RPAREN,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1030] = 1,
    ACTIONS(57), 10,
      anon_sym_LT,
      anon_sym_LT_EQ,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [1043] = 2,
    ACTIONS(65), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(63), 8,
      aux_sym_Stmt_token2,
      anon_sym_RPAREN,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
  [1058] = 2,
    ACTIONS(85), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(51), 8,
      anon_sym_LT,
      anon_sym_LT_EQ,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [1073] = 1,
    ACTIONS(35), 10,
      anon_sym_LT,
      anon_sym_LT_EQ,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [1086] = 2,
    ACTIONS(85), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(77), 8,
      anon_sym_LT,
      anon_sym_LT_EQ,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [1101] = 1,
    ACTIONS(47), 10,
      anon_sym_LT,
      anon_sym_LT_EQ,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [1114] = 1,
    ACTIONS(61), 10,
      anon_sym_LT,
      anon_sym_LT_EQ,
      anon_sym_GT,
      anon_sym_GT_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [1127] = 3,
    ACTIONS(91), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(87), 3,
      ts_builtin_sym_end,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
    ACTIONS(89), 4,
      aux_sym_Stmt_token1,
      anon_sym_LT,
      anon_sym_GT,
      sym_ID,
  [1143] = 7,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_ID,
    STATE(46), 1,
      sym_MultiplicativeExpr,
    STATE(47), 1,
      sym_Primary,
    STATE(48), 1,
      sym_UnaryExpr,
    STATE(72), 1,
      sym_AdditiveExpr,
    ACTIONS(25), 2,
      sym_STR,
      sym_NUM,
  [1166] = 2,
    ACTIONS(93), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(89), 6,
      anon_sym_LT,
      anon_sym_LT_EQ,
      anon_sym_GT,
      anon_sym_GT_EQ,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [1179] = 7,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      sym_ID,
    STATE(19), 1,
      sym_Primary,
    STATE(22), 1,
      sym_UnaryExpr,
    STATE(28), 1,
      sym_MultiplicativeExpr,
    STATE(67), 1,
      sym_AdditiveExpr,
    ACTIONS(31), 2,
      sym_STR,
      sym_NUM,
  [1202] = 7,
    ACTIONS(5), 1,
      aux_sym_Stmt_token1,
    ACTIONS(7), 1,
      sym_ID,
    ACTIONS(95), 1,
      ts_builtin_sym_end,
    STATE(74), 1,
      sym_ExprStatement,
    STATE(85), 1,
      sym_MoreThanOneStmt,
    STATE(89), 1,
      sym_Stmt,
    STATE(55), 2,
      sym_Prog,
      aux_sym_Start_repeat1,
  [1225] = 3,
    ACTIONS(89), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(97), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(87), 4,
      aux_sym_Stmt_token2,
      anon_sym_RPAREN,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1240] = 7,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 1,
      aux_sym_Stmt_token1,
    ACTIONS(104), 1,
      sym_ID,
    STATE(74), 1,
      sym_ExprStatement,
    STATE(85), 1,
      sym_MoreThanOneStmt,
    STATE(89), 1,
      sym_Stmt,
    STATE(55), 2,
      sym_Prog,
      aux_sym_Start_repeat1,
  [1263] = 7,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_ID,
    STATE(32), 1,
      sym_MultiplicativeExpr,
    STATE(36), 1,
      sym_UnaryExpr,
    STATE(37), 1,
      sym_Primary,
    STATE(70), 1,
      sym_AdditiveExpr,
    ACTIONS(15), 2,
      sym_STR,
      sym_NUM,
  [1286] = 6,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      sym_ID,
    STATE(19), 1,
      sym_Primary,
    STATE(20), 1,
      sym_MultiplicativeExpr,
    STATE(22), 1,
      sym_UnaryExpr,
    ACTIONS(31), 2,
      sym_STR,
      sym_NUM,
  [1306] = 4,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
    ACTIONS(109), 2,
      aux_sym_Stmt_token1,
      sym_ID,
    ACTIONS(111), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(113), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1322] = 6,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_ID,
    STATE(36), 1,
      sym_UnaryExpr,
    STATE(37), 1,
      sym_Primary,
    STATE(40), 1,
      sym_MultiplicativeExpr,
    ACTIONS(15), 2,
      sym_STR,
      sym_NUM,
  [1342] = 6,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_ID,
    STATE(44), 1,
      sym_MultiplicativeExpr,
    STATE(47), 1,
      sym_Primary,
    STATE(48), 1,
      sym_UnaryExpr,
    ACTIONS(25), 2,
      sym_STR,
      sym_NUM,
  [1362] = 5,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_ID,
    STATE(42), 1,
      sym_UnaryExpr,
    STATE(47), 1,
      sym_Primary,
    ACTIONS(25), 2,
      sym_STR,
      sym_NUM,
  [1379] = 2,
    ACTIONS(109), 2,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
    ACTIONS(115), 4,
      anon_sym_LT,
      anon_sym_LT_EQ,
      anon_sym_GT,
      anon_sym_GT_EQ,
  [1390] = 3,
    ACTIONS(107), 2,
      aux_sym_Stmt_token2,
      anon_sym_RPAREN,
    ACTIONS(117), 2,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(119), 2,
      anon_sym_LT_EQ,
      anon_sym_GT_EQ,
  [1403] = 5,
    ACTIONS(27), 1,
      anon_sym_LPAREN,
    ACTIONS(29), 1,
      sym_ID,
    STATE(19), 1,
      sym_Primary,
    STATE(21), 1,
      sym_UnaryExpr,
    ACTIONS(31), 2,
      sym_STR,
      sym_NUM,
  [1420] = 5,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      sym_ID,
    STATE(37), 1,
      sym_Primary,
    STATE(41), 1,
      sym_UnaryExpr,
    ACTIONS(15), 2,
      sym_STR,
      sym_NUM,
  [1437] = 5,
    ACTIONS(121), 1,
      aux_sym_Stmt_token1,
    ACTIONS(123), 1,
      sym_ID,
    STATE(84), 1,
      sym_Stmt,
    STATE(107), 1,
      sym_ExprStatement,
    STATE(124), 1,
      sym_TheRest,
  [1453] = 3,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    ACTIONS(91), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(127), 2,
      aux_sym_Stmt_token1,
      sym_ID,
  [1465] = 5,
    ACTIONS(121), 1,
      aux_sym_Stmt_token1,
    ACTIONS(123), 1,
      sym_ID,
    STATE(84), 1,
      sym_Stmt,
    STATE(107), 1,
      sym_ExprStatement,
    STATE(120), 1,
      sym_TheRest,
  [1481] = 3,
    STATE(66), 1,
      sym_CR,
    STATE(75), 1,
      sym_CRStmtCRs,
    ACTIONS(129), 2,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [1492] = 2,
    ACTIONS(97), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(125), 2,
      aux_sym_Stmt_token2,
      anon_sym_RPAREN,
  [1501] = 3,
    STATE(66), 1,
      sym_CR,
    STATE(80), 1,
      sym_CRStmtCRs,
    ACTIONS(129), 2,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [1512] = 2,
    ACTIONS(93), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(127), 2,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [1521] = 2,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    ACTIONS(133), 2,
      aux_sym_Stmt_token1,
      sym_ID,
  [1529] = 2,
    ACTIONS(135), 1,
      ts_builtin_sym_end,
    ACTIONS(137), 2,
      aux_sym_Stmt_token1,
      sym_ID,
  [1537] = 3,
    ACTIONS(139), 1,
      sym_EndIf,
    STATE(91), 1,
      sym_MoreThanZeroElseIf,
    STATE(100), 1,
      sym_OptionalElse,
  [1547] = 2,
    ACTIONS(141), 1,
      ts_builtin_sym_end,
    ACTIONS(143), 2,
      aux_sym_Stmt_token1,
      sym_ID,
  [1555] = 2,
    ACTIONS(145), 1,
      ts_builtin_sym_end,
    ACTIONS(147), 2,
      aux_sym_Stmt_token1,
      sym_ID,
  [1563] = 2,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
    ACTIONS(151), 2,
      aux_sym_Stmt_token1,
      sym_ID,
  [1571] = 2,
    ACTIONS(153), 1,
      ts_builtin_sym_end,
    ACTIONS(155), 2,
      aux_sym_Stmt_token1,
      sym_ID,
  [1579] = 3,
    ACTIONS(157), 1,
      sym_EndIf,
    STATE(82), 1,
      sym_MoreThanZeroElseIf,
    STATE(83), 1,
      sym_OptionalElse,
  [1589] = 2,
    ACTIONS(159), 1,
      ts_builtin_sym_end,
    ACTIONS(161), 2,
      aux_sym_Stmt_token1,
      sym_ID,
  [1597] = 2,
    ACTIONS(163), 1,
      ts_builtin_sym_end,
    ACTIONS(165), 2,
      aux_sym_Stmt_token1,
      sym_ID,
  [1605] = 2,
    ACTIONS(167), 1,
      ts_builtin_sym_end,
    ACTIONS(169), 2,
      aux_sym_Stmt_token1,
      sym_ID,
  [1613] = 2,
    STATE(68), 1,
      sym_CR,
    ACTIONS(129), 2,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [1621] = 2,
    ACTIONS(171), 1,
      ts_builtin_sym_end,
    ACTIONS(173), 2,
      aux_sym_Stmt_token1,
      sym_ID,
  [1629] = 3,
    ACTIONS(175), 1,
      anon_sym_EQ,
    ACTIONS(177), 1,
      anon_sym_DOT,
    ACTIONS(179), 1,
      anon_sym_LPAREN,
  [1639] = 2,
    ACTIONS(181), 1,
      ts_builtin_sym_end,
    ACTIONS(183), 2,
      aux_sym_Stmt_token1,
      sym_ID,
  [1647] = 3,
    ACTIONS(185), 1,
      anon_sym_EQ,
    ACTIONS(187), 1,
      anon_sym_DOT,
    ACTIONS(189), 1,
      anon_sym_LPAREN,
  [1657] = 2,
    ACTIONS(191), 1,
      ts_builtin_sym_end,
    ACTIONS(193), 2,
      aux_sym_Stmt_token1,
      sym_ID,
  [1665] = 2,
    ACTIONS(195), 1,
      ts_builtin_sym_end,
    ACTIONS(197), 2,
      aux_sym_Stmt_token1,
      sym_ID,
  [1673] = 1,
    ACTIONS(165), 2,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [1678] = 1,
    ACTIONS(147), 2,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [1683] = 1,
    ACTIONS(143), 2,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [1688] = 2,
    ACTIONS(199), 1,
      anon_sym_EQ,
    ACTIONS(201), 1,
      anon_sym_LPAREN,
  [1695] = 1,
    ACTIONS(151), 2,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [1700] = 1,
    ACTIONS(133), 2,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [1705] = 1,
    ACTIONS(155), 2,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [1710] = 1,
    ACTIONS(183), 2,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [1715] = 1,
    ACTIONS(197), 2,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [1720] = 1,
    ACTIONS(169), 2,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [1725] = 1,
    ACTIONS(149), 2,
      aux_sym_Stmt_token2,
      anon_sym_RPAREN,
  [1730] = 1,
    ACTIONS(161), 2,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [1735] = 1,
    ACTIONS(203), 2,
      aux_sym_Stmt_token1,
      sym_ID,
  [1740] = 2,
    ACTIONS(205), 1,
      anon_sym_EQ,
    ACTIONS(207), 1,
      anon_sym_LPAREN,
  [1747] = 1,
    ACTIONS(153), 2,
      aux_sym_Stmt_token2,
      anon_sym_RPAREN,
  [1752] = 1,
    ACTIONS(141), 2,
      aux_sym_Stmt_token2,
      anon_sym_RPAREN,
  [1757] = 1,
    ACTIONS(137), 2,
      aux_sym_CR_token1,
      aux_sym_CR_token2,
  [1762] = 1,
    ACTIONS(145), 2,
      aux_sym_Stmt_token2,
      anon_sym_RPAREN,
  [1767] = 1,
    ACTIONS(209), 1,
      anon_sym_RPAREN,
  [1771] = 1,
    ACTIONS(211), 1,
      anon_sym_RPAREN,
  [1775] = 1,
    ACTIONS(213), 1,
      anon_sym_RPAREN,
  [1779] = 1,
    ACTIONS(215), 1,
      sym_ID,
  [1783] = 1,
    ACTIONS(217), 1,
      anon_sym_RPAREN,
  [1787] = 1,
    ACTIONS(219), 1,
      sym_ID,
  [1791] = 1,
    ACTIONS(221), 1,
      anon_sym_RPAREN,
  [1795] = 1,
    ACTIONS(223), 1,
      anon_sym_RPAREN,
  [1799] = 1,
    ACTIONS(225), 1,
      anon_sym_RPAREN,
  [1803] = 1,
    ACTIONS(227), 1,
      anon_sym_RPAREN,
  [1807] = 1,
    ACTIONS(229), 1,
      sym_ID,
  [1811] = 1,
    ACTIONS(231), 1,
      sym_EndIf,
  [1815] = 1,
    ACTIONS(233), 1,
      anon_sym_RPAREN,
  [1819] = 1,
    ACTIONS(235), 1,
      sym_ID,
  [1823] = 1,
    ACTIONS(237), 1,
      aux_sym_Stmt_token2,
  [1827] = 1,
    ACTIONS(239), 1,
      sym_EndIf,
  [1831] = 1,
    ACTIONS(241), 1,
      anon_sym_RPAREN,
  [1835] = 1,
    ACTIONS(243), 1,
      anon_sym_RPAREN,
  [1839] = 1,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
  [1843] = 1,
    ACTIONS(247), 1,
      aux_sym_Stmt_token2,
  [1847] = 1,
    ACTIONS(249), 1,
      sym_ID,
  [1851] = 1,
    ACTIONS(251), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 50,
  [SMALL_STATE(4)] = 100,
  [SMALL_STATE(5)] = 150,
  [SMALL_STATE(6)] = 197,
  [SMALL_STATE(7)] = 244,
  [SMALL_STATE(8)] = 285,
  [SMALL_STATE(9)] = 326,
  [SMALL_STATE(10)] = 367,
  [SMALL_STATE(11)] = 408,
  [SMALL_STATE(12)] = 449,
  [SMALL_STATE(13)] = 490,
  [SMALL_STATE(14)] = 531,
  [SMALL_STATE(15)] = 572,
  [SMALL_STATE(16)] = 613,
  [SMALL_STATE(17)] = 632,
  [SMALL_STATE(18)] = 651,
  [SMALL_STATE(19)] = 667,
  [SMALL_STATE(20)] = 683,
  [SMALL_STATE(21)] = 701,
  [SMALL_STATE(22)] = 717,
  [SMALL_STATE(23)] = 733,
  [SMALL_STATE(24)] = 749,
  [SMALL_STATE(25)] = 765,
  [SMALL_STATE(26)] = 781,
  [SMALL_STATE(27)] = 797,
  [SMALL_STATE(28)] = 815,
  [SMALL_STATE(29)] = 833,
  [SMALL_STATE(30)] = 851,
  [SMALL_STATE(31)] = 867,
  [SMALL_STATE(32)] = 880,
  [SMALL_STATE(33)] = 897,
  [SMALL_STATE(34)] = 912,
  [SMALL_STATE(35)] = 925,
  [SMALL_STATE(36)] = 940,
  [SMALL_STATE(37)] = 955,
  [SMALL_STATE(38)] = 970,
  [SMALL_STATE(39)] = 983,
  [SMALL_STATE(40)] = 998,
  [SMALL_STATE(41)] = 1015,
  [SMALL_STATE(42)] = 1030,
  [SMALL_STATE(43)] = 1043,
  [SMALL_STATE(44)] = 1058,
  [SMALL_STATE(45)] = 1073,
  [SMALL_STATE(46)] = 1086,
  [SMALL_STATE(47)] = 1101,
  [SMALL_STATE(48)] = 1114,
  [SMALL_STATE(49)] = 1127,
  [SMALL_STATE(50)] = 1143,
  [SMALL_STATE(51)] = 1166,
  [SMALL_STATE(52)] = 1179,
  [SMALL_STATE(53)] = 1202,
  [SMALL_STATE(54)] = 1225,
  [SMALL_STATE(55)] = 1240,
  [SMALL_STATE(56)] = 1263,
  [SMALL_STATE(57)] = 1286,
  [SMALL_STATE(58)] = 1306,
  [SMALL_STATE(59)] = 1322,
  [SMALL_STATE(60)] = 1342,
  [SMALL_STATE(61)] = 1362,
  [SMALL_STATE(62)] = 1379,
  [SMALL_STATE(63)] = 1390,
  [SMALL_STATE(64)] = 1403,
  [SMALL_STATE(65)] = 1420,
  [SMALL_STATE(66)] = 1437,
  [SMALL_STATE(67)] = 1453,
  [SMALL_STATE(68)] = 1465,
  [SMALL_STATE(69)] = 1481,
  [SMALL_STATE(70)] = 1492,
  [SMALL_STATE(71)] = 1501,
  [SMALL_STATE(72)] = 1512,
  [SMALL_STATE(73)] = 1521,
  [SMALL_STATE(74)] = 1529,
  [SMALL_STATE(75)] = 1537,
  [SMALL_STATE(76)] = 1547,
  [SMALL_STATE(77)] = 1555,
  [SMALL_STATE(78)] = 1563,
  [SMALL_STATE(79)] = 1571,
  [SMALL_STATE(80)] = 1579,
  [SMALL_STATE(81)] = 1589,
  [SMALL_STATE(82)] = 1597,
  [SMALL_STATE(83)] = 1605,
  [SMALL_STATE(84)] = 1613,
  [SMALL_STATE(85)] = 1621,
  [SMALL_STATE(86)] = 1629,
  [SMALL_STATE(87)] = 1639,
  [SMALL_STATE(88)] = 1647,
  [SMALL_STATE(89)] = 1657,
  [SMALL_STATE(90)] = 1665,
  [SMALL_STATE(91)] = 1673,
  [SMALL_STATE(92)] = 1678,
  [SMALL_STATE(93)] = 1683,
  [SMALL_STATE(94)] = 1688,
  [SMALL_STATE(95)] = 1695,
  [SMALL_STATE(96)] = 1700,
  [SMALL_STATE(97)] = 1705,
  [SMALL_STATE(98)] = 1710,
  [SMALL_STATE(99)] = 1715,
  [SMALL_STATE(100)] = 1720,
  [SMALL_STATE(101)] = 1725,
  [SMALL_STATE(102)] = 1730,
  [SMALL_STATE(103)] = 1735,
  [SMALL_STATE(104)] = 1740,
  [SMALL_STATE(105)] = 1747,
  [SMALL_STATE(106)] = 1752,
  [SMALL_STATE(107)] = 1757,
  [SMALL_STATE(108)] = 1762,
  [SMALL_STATE(109)] = 1767,
  [SMALL_STATE(110)] = 1771,
  [SMALL_STATE(111)] = 1775,
  [SMALL_STATE(112)] = 1779,
  [SMALL_STATE(113)] = 1783,
  [SMALL_STATE(114)] = 1787,
  [SMALL_STATE(115)] = 1791,
  [SMALL_STATE(116)] = 1795,
  [SMALL_STATE(117)] = 1799,
  [SMALL_STATE(118)] = 1803,
  [SMALL_STATE(119)] = 1807,
  [SMALL_STATE(120)] = 1811,
  [SMALL_STATE(121)] = 1815,
  [SMALL_STATE(122)] = 1819,
  [SMALL_STATE(123)] = 1823,
  [SMALL_STATE(124)] = 1827,
  [SMALL_STATE(125)] = 1831,
  [SMALL_STATE(126)] = 1835,
  [SMALL_STATE(127)] = 1839,
  [SMALL_STATE(128)] = 1843,
  [SMALL_STATE(129)] = 1847,
  [SMALL_STATE(130)] = 1851,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Start, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Primary, 1),
  [35] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_Primary, 1),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Primary, 3),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_Primary, 3),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_UnaryExpr, 1),
  [47] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_UnaryExpr, 1),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_AdditiveExpr, 3),
  [51] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_AdditiveExpr, 3),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_MultiplicativeExpr, 3),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_MultiplicativeExpr, 3),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_MultiplicativeExpr, 1),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_MultiplicativeExpr, 1),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Primary, 5),
  [65] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_Primary, 5),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Primary, 6),
  [69] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_Primary, 6),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_AdditiveExpr, 1),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_AdditiveExpr, 1),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_CompExpr, 1),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_CompExpr, 1),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Start, 1),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_Start_repeat1, 2),
  [101] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_Start_repeat1, 2), SHIFT_REPEAT(13),
  [104] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_Start_repeat1, 2), SHIFT_REPEAT(88),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_EqNeqExpr, 1),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_EqNeqExpr, 1),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_EqNeqExpr, 3),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_EqNeqExpr, 3),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ExprStatement, 3),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ExprStatement, 3),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Stmt, 1),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_Stmt, 1),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_AndExpr, 1),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_AndExpr, 1),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_OrExpr, 1),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_OrExpr, 1),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_CondExpr, 1),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_CondExpr, 1),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Expr, 1),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_Expr, 1),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_OptionalElse, 1),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_OptionalElse, 1),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Stmt, 5),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_Stmt, 5),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_MoreThanZeroElseIf, 1),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_MoreThanZeroElseIf, 1),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Prog, 1),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_Prog, 1),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ExprStatement, 6),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ExprStatement, 6),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_MoreThanOneStmt, 1),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_MoreThanOneStmt, 1),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_ExprStatement, 5),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_ExprStatement, 5),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_CR, 1),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_TheRest, 3),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [235] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_CRStmtCRs, 2),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_Exprs, 1),
  [245] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_MoreThanOneExpr, 1),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [251] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_nodejs(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
